service: second-test

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  role: arn:aws:iam::624733648801:role/Role-serverless-function
  

package:
  individually: true
  exclude:
    - "**"
  
functions:
  hello:
    handler: lambdas/handler.hello
    events:
      - s3:
          bucket: codebuildjuver
          event: s3:ObjectCreated:*
          rules:
            - prefix: lambdas/
            - suffix: "*"
          existing: true
    package:
      include:
        - lambdas/handler.py
   
  hello2:
    handler: lambda2/handler.hello2
    package:
      include:
        - lambda2/handler.py

  
     

