service: second-test

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
     package:
      exclude:
        - /codebuild/output/src616022190/src/README.md
        - /codebuild/output/src616022190/src/codebuild.yml
        - /codebuild/output/src616022190/src/policy.json
        - /codebuild/output/src616022190/src/template_F&B.yml

