service: second-test

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
     package:
      exclude:
        - TestFB/README.md
        - TestFB/codebuild.yml
        - TestFB/policy.json
        - TestFB/template_F&B.yml

