service: second-test

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

package:
  individually: true
  
functions:
  hello:
    handler: lambdas/handler.hello
    package:
      include: 
        - lambdas/**
    

  
     

