service: second-test

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
     package:
      exclude:
        - /README.md
        - /codebuild.yml
        - /policy.json
        - /template_F&B.yml

