service: second-test

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

package:
  # include:
  #  - include-me.py
   # - include-me-dir/**
  exclude:
    - lambda2/** # exclude
functions:
  hello:
    handler: lambdas/handler.hello
    

  
     

