service: example    ## Must be name of the of project. Lamba Fn names will be prefixed with this value. 

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  role: arn:aws:iam::624733648801:role/Role-serverless-function
  stage: test
  deploymentPrefix: serverless
  deploymentBucket:
    name: codebuildjuver
    tags: 
      project: example
    
plugins:
  - serverless-deployment-bucket
  
package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - "**"
   
functions:
  Orchest:
    handler: lambdas/lambda_orchest.inference
    events:
      - http:
          path: /inference
          method: get
          
    package:
      include:
        - */lambda_orchest.py
        
  lambda-01:
    handler: lambdas/lambda_01.greetings
    package:
      include:
        - lambdas/lambda_01.py

  lambda-02:
    handler: lambdas/lambda_02.greetings
    package:
      include:
        - lambdas/lambda_02.py

  lambda-03:
    handler: lambdas/lambda_03.greetings
    package:
      include:
        - lambdas/lambda_03.py

  lambda-sqs:
    handler: lambdas/lambda_sqs.greetings
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - exampleServerlessQueue
              - Arn
    package:
      include:
        - lambdas/lambda_sqs.py
        
  lambda-sns:
    handler: lambdas/lambda_sns.greetings
    events:
      - sns:
          arn: !Ref exampleServerlessTopic
          topicName: exampleServerlessTopicTest
    package:
      include:
        - lambdas/lambda_sns.py
  
  lambda-kinesis:
    handler: lambdas/lambda_kinesis.greetings
    events:
      - stream:
          type: kinesis
          batchSize: 50
          arn:
            Fn::GetAtt:
              - KinesisStream
              - Arn
    package:
      include:
        - lambdas/lambda_kinesis.py

resources:
  Resources:
    exampleServerlessQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: exampleServerlessQueueTest
    exampleServerlessTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: exampleServerlessTopicTest
    KinesisStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: exampleKinesisStream
        ShardCount: 1
